apiVersion: v1
kind: Pod
metadata:
  name: pod0
  namespace: dra-tutorial
  labels:
    app: pod
  annotations:
    io.containerd.cri.runtime-handler: "kata-qemu-coco-dev"
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
  - name: ctr0
    image: busybox:stable-uclibc
    imagePullPolicy: Always
    command:
      - sleep
      - "infinity"
    #image: ubuntu:24.04
    #command: ["bash", "-c"]
    #args: ["export; trap 'exit 0' TERM; sleep 9999 & wait"]
    resources:
      claims:
      - name: gpu
  resourceClaims:
  - name: gpu
    resourceClaimName: some-gpu